// <auto-generated />
namespace BookShop.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class updateOrdertotaldataType : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(updateOrdertotaldataType));
        
        string IMigrationMetadata.Id
        {
            get { return "201801291426364_update-Order-total-dataType"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
